### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by minhakSilp** [17-1-SKKU-OSS/063B#2]
새로운 모드를 만들것인가 아니면 기존의 모드를 수정할 것인가 그것이 문제로다

**Comment by juliet152** [comment]
일단은 새로운 모드를 생각하고 가는게 낫지 않을지?

**Comment by nelpsos** [comment]
새로운 모드가 확실히 재미는 있을 것 같아요

**Comment by nelpsos** [comment]
근데 새로운 모드는 아이디어가 필요해서...
일단 여러분도 픽셀 던전 좀 해 보고 이야기해보죠

**Comment by juliet152** [comment]
뭔가 컨셉이 있어야지. 픽셀던전 모드 하고싶었던데는 뭔가 이유가 있었던거 아님?

**Comment by nelpsos** [comment]
그냥 좋아하는 오픈소스 프로젝트가 이거 하나뿐이었던 게 사실 큰 이윤데.

**Comment by nelpsos** [comment]
새 모드를 만들려면 픽셀 던전을 고르고,
풀 리퀘스트를 넣으려면 섀터드 픽셀 던전을 골라야 하는데,
봐야 하는 코드의 양이 픽셀 던전 쪽이 훨씬 적을 테니 새 모드를 고르는 걸로 하자.
