### ISSUE TITLE
무슨 모드를 만들까?

### ISSUE THREAD

**Issue by nelpsos** [17-1-SKKU-OSS/063B#3]
몇 가지 안이 있는데.

1. 새로운 직업을 만든다. 그 직업만 플레이 가능하게 한다.
2. 플레이 방식을 바꾼다. 이건 좀 어려울 것 같아.
3. 새로운 메커니즘의 아이템을 만든다. 이게 사실상 가장 현실적일 듯.
4. 밸런스를 붕괴시킨다. 템드랍률을 엄청나게 상승시킨다든가, 특정 아이템만 쥰내게 떨어진다든가.
5. 맵을 바꾼다.
6. 그래픽을 바꾼다.
7. 새로운 적을 만든다.
8. 원래 26층이 엔딩인데, 26층 이후를 만든다.
9. 로그라이크 게임 이외의 컨텐츠(엔딩을 본 회수에 따른 파밍 컨텐츠라든지)를 만든다.

**Comment by nelpsos** [comment]
몇 개든 중복 선택해도 괜찮겠지만, 여러 개를 선택하면 어렵겠죠?

**Comment by juliet152** [comment]
Frozen Pixel Dungeon

**Comment by nelpsos** [comment]
얼어붙은 픽셀 던전

- 얼음 타일은 밟으면 미끄러집니다! 조심하세요. 아이젠을 신으면 얼음 발판에도 안전할 수 있습니다. 얼음 타일에 a턴간 있다면, 동상에도 걸릴 수 있겠죠.
- 주의: 고드름이 떨어집니다. 고드름은 생긴 지 n턴 뒤에 떨어지고, 떨어지고 나면 m턴간 얼음 타일이 됩니다.
- 새로운 상태이상: 동상. 손이 시려워, 꽁! 발이 시려워, 꽁! 동상은 이동속도와 공격속도를 느려지게 합니다. 동상을 풀기 위한 몇 가지 아이템도 등장합니다.
- 특정 층에서는 눈보라가 붑니다! 눈보라는 시야를 가리며, a턴간 눈보라를 무방비하게 맞는다면 동상에 걸릴 수도 있습니다. 눈보라는 불었다 그쳤다 하며, 눈보라를 맞지 않기 위한 움직임이 요구됩니다.

**Comment by minhakSilp** [comment]
추가할 만한 사항
- 포션이 얼음 포션으로 바뀐다.

**Comment by nelpsos** [comment]
- 횃불이 동상을 풀기도 하고, 얼어붙은 적에게 추가 피해를 줍니다.
