### ISSUE TITLE
픽셀 던전 교양

### ISSUE THREAD

**Issue by nelpsos** [17-1-SKKU-OSS/063B#5]
포크해오는 법(아마 쓸모없음)
http://lifove.tistory.com/54

픽셀 던전 다운로드(윈도우즈, 리눅스, MacOS, 안드로이드, iOS 지원)
http://pixeldungeon.watabou.ru/

자바 런타임 환경 다운로드(리눅스, MacOS에서 픽셀 던전 구동시 필요)
https://java.com/en/download/linux_manual.jsp

**Comment by nelpsos** [comment]
! 데스크탑에서 실행 가능한 버전은 1.7.2버전으로, 최신 버전이 아닙니다 !
완전한 경험이 하고 싶으시다면, 안드로이드 버전을 사용하세요.
iOS에서 하고 싶으시면... 제가 돈 대드릴테니 사세요.

**Comment by nelpsos** [comment]
스팀에서 사서 해 봤더니 최신버전입니다.
스팀 버전 이용하시면 제가 돈 대드림. 스팀버전은 데스크탑에 최적화도 잘 되어 있음.
한글로 하고 싶으시면 Shattered Pixel Dungeon 해 보셔도 됨

**Comment by juliet152** [comment]
나무위키
https://namu.wiki/w/%ED%94%BD%EC%85%80%20%EB%8D%98%EC%A0%84?from=%ED%94%BD%EC%85%80%EB%8D%98%EC%A0%84

픽셀위키
http://pixeldungeon.wikia.com/wiki/Main_Page
